/**
 * WeaponData.ts — Complete weapon definitions.
 * Mirrors WeaponData.lua — all 22 weapons from original Lua source.
 */

import { DAMAGE_TYPE, ATTACK_TYPE } from '../characters/CharacterConstants';

export interface WeaponDef {
  sName: string;
  friendlyName: string;
  nDamage: number;
  nDamageType: number;
  nAttackType: number;
  nRange: number;
  /** Stance: melee, pistol, rifle, stunner */
  sStance: string;
  /** Points value (rarity/desirability). */
  nPoints: number;
  /** Aim time range (seconds). Default: 0.5-1.5 for ranged. */
  nMinAimTime?: number;
  nMaxAimTime?: number;
  /** Cooldown range (seconds). Default: 1-2 for ranged. */
  nMinCoolDown?: number;
  nMaxCoolDown?: number;
  /** Melee-specific cooldown. */
  nMeleeCoolDown?: number;
  /** Is a job tool (equippable by security). */
  bJobTool?: boolean;
  /** Is a collectible "stuff" item. */
  bStuff?: boolean;
  /** Disappears when dropped (hostile-only weapons). */
  bDisappearOnDrop?: boolean;
  /** Bullet sprite name for ranged weapons. */
  sBulletSprite?: string;
  /** Projectile speed (tiles/sec). */
  nProjectileSpeed: number;
  /** Shots per second (derived from cooldown for compat). */
  nFireRate: number;
}

export const WEAPON_DEFS: Record<string, WeaponDef> = {
  // ── Melee weapons ──────────────────────────────────────────────────────────
  Fists: {
    sName: 'Fists',
    friendlyName: 'Fists',
    nDamage: 10,
    nDamageType: DAMAGE_TYPE.Melee,
    nAttackType: ATTACK_TYPE.Grapple,
    sStance: 'melee',
    nRange: 0,
    nPoints: 0,
    nProjectileSpeed: 0,
    nFireRate: 1,
  },
  PunchingGloves: {
    sName: 'PunchingGloves',
    friendlyName: 'Punching Gloves',
    nDamage: 30,
    nDamageType: DAMAGE_TYPE.Stunner,
    nAttackType: ATTACK_TYPE.Grapple,
    sStance: 'melee',
    nRange: 0,
    nPoints: 4,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 0,
    nFireRate: 1,
  },
  VibroKnife: {
    sName: 'VibroKnife',
    friendlyName: 'Vibro Knife',
    nDamage: 40,
    nDamageType: DAMAGE_TYPE.Melee,
    nAttackType: ATTACK_TYPE.Grapple,
    sStance: 'melee',
    nRange: 0,
    nPoints: 4,
    nMeleeCoolDown: 1,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 0,
    nFireRate: 1,
  },
  CryoVise: {
    sName: 'CryoVise',
    friendlyName: 'Cryo Vise',
    nDamage: 25,
    nDamageType: DAMAGE_TYPE.Melee,
    nAttackType: ATTACK_TYPE.Grapple,
    sStance: 'melee',
    nRange: 0,
    nPoints: 2,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 0,
    nFireRate: 1,
  },
  Uberfist: {
    sName: 'Uberfist',
    friendlyName: 'Uberfist',
    nDamage: 15,
    nDamageType: DAMAGE_TYPE.Impact,
    nAttackType: ATTACK_TYPE.Grapple,
    sStance: 'melee',
    nRange: 0,
    nPoints: 1,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 0,
    nFireRate: 1,
  },

  // ── Short-range melee/hybrid ───────────────────────────────────────────────
  Rey5w0rd: {
    sName: 'Rey5w0rd',
    friendlyName: 'Rey5w0rd',
    nDamage: 40,
    nDamageType: DAMAGE_TYPE.Impact,
    nAttackType: ATTACK_TYPE.Grapple,
    sStance: 'melee',
    nRange: 3,
    nPoints: 4,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 0,
    nFireRate: 1,
  },
  Sonicdirk: {
    sName: 'Sonicdirk',
    friendlyName: 'Sonicdirk',
    nDamage: 30,
    nDamageType: DAMAGE_TYPE.Laser,
    nAttackType: ATTACK_TYPE.Grapple,
    sStance: 'melee',
    nRange: 4,
    nPoints: 4,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 0,
    nFireRate: 1,
  },

  // ── Pistols ────────────────────────────────────────────────────────────────
  Pistol: {
    sName: 'Pistol',
    friendlyName: 'Pistol',
    nDamage: 15,
    nDamageType: DAMAGE_TYPE.Laser,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'pistol',
    nRange: 18,
    nPoints: 1,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 10,
    nFireRate: 0.5,
  },
  LaserPistol: {
    sName: 'LaserPistol',
    friendlyName: 'Laser Pistol',
    nDamage: 15,
    nDamageType: DAMAGE_TYPE.Laser,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'pistol',
    nRange: 8,
    nPoints: 1,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 10,
    nFireRate: 0.5,
  },
  AutoPistol: {
    sName: 'AutoPistol',
    friendlyName: 'Auto Pistol',
    nDamage: 5,
    nDamageType: DAMAGE_TYPE.Laser,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'pistol',
    nRange: 8,
    nPoints: 2,
    nMinAimTime: 0.05,
    nMaxAimTime: 0.1,
    nMinCoolDown: 0.01,
    nMaxCoolDown: 0.1,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 10,
    nFireRate: 10,
  },
  RedPistol: {
    sName: 'RedPistol',
    friendlyName: 'Red Pistol',
    nDamage: 20,
    nDamageType: DAMAGE_TYPE.Laser,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'pistol',
    nRange: 15,
    nPoints: 1,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 10,
    nFireRate: 0.5,
  },
  TeleMag44: {
    sName: 'TeleMag44',
    friendlyName: 'TeleMag 44',
    nDamage: 25,
    nDamageType: DAMAGE_TYPE.Laser,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'pistol',
    nRange: 20,
    nPoints: 2,
    nMinAimTime: 0.5,
    nMaxAimTime: 1,
    nMinCoolDown: 1,
    nMaxCoolDown: 5,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 12,
    nFireRate: 0.3,
  },
  Nebuliser: {
    sName: 'Nebuliser',
    friendlyName: 'Nebuliser',
    nDamage: 30,
    nDamageType: DAMAGE_TYPE.Fire,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'pistol',
    nRange: 15,
    nPoints: 3,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 10,
    nFireRate: 0.5,
  },

  // ── Stunners ───────────────────────────────────────────────────────────────
  Stunner: {
    sName: 'Stunner',
    friendlyName: 'Stunner',
    nDamage: 15,
    nDamageType: DAMAGE_TYPE.Stunner,
    nAttackType: ATTACK_TYPE.Stunner,
    sStance: 'stunner',
    nRange: 3,
    nPoints: 1,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 8,
    nFireRate: 0.7,
  },
  SuperStunner: {
    sName: 'SuperStunner',
    friendlyName: 'Super Stunner',
    nDamage: 30,
    nDamageType: DAMAGE_TYPE.Stunner,
    nAttackType: ATTACK_TYPE.Stunner,
    sStance: 'stunner',
    nRange: 6,
    nPoints: 3,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 10,
    nFireRate: 0.5,
  },
  Sling_of_Truth: {
    sName: 'Sling_of_Truth',
    friendlyName: 'Sling of Truth',
    nDamage: 40,
    nDamageType: DAMAGE_TYPE.Stunner,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'pistol',
    nRange: 15,
    nPoints: 4,
    nMinAimTime: 1,
    nMaxAimTime: 3,
    nMinCoolDown: 1,
    nMaxCoolDown: 5,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 10,
    nFireRate: 0.3,
  },
  Schizodestroyer: {
    sName: 'Schizodestroyer',
    friendlyName: 'Schizodestroyer',
    nDamage: 20,
    nDamageType: DAMAGE_TYPE.Stunner,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'rifle',
    nRange: 10,
    nPoints: 2,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 10,
    nFireRate: 0.5,
  },

  // ── Rifles ─────────────────────────────────────────────────────────────────
  LaserRifle: {
    sName: 'LaserRifle',
    friendlyName: 'Laser Rifle',
    nDamage: 30,
    nDamageType: DAMAGE_TYPE.Laser,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'rifle',
    nRange: 18,
    nPoints: 3,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 12,
    nFireRate: 0.3,
  },
  RedLaserRifle: {
    sName: 'RedLaserRifle',
    friendlyName: 'Red Laser Rifle',
    nDamage: 30,
    nDamageType: DAMAGE_TYPE.Laser,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'rifle',
    nRange: 18,
    nPoints: 3,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 12,
    nFireRate: 0.3,
  },
  PlasmaRifle: {
    sName: 'PlasmaRifle',
    friendlyName: 'Plasma Rifle',
    nDamage: 45,
    nDamageType: DAMAGE_TYPE.Laser,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'rifle',
    nRange: 18,
    nPoints: 4,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 12,
    nFireRate: 0.3,
  },
  SniperRifle: {
    sName: 'SniperRifle',
    friendlyName: 'Sniper Rifle',
    nDamage: 50,
    nDamageType: DAMAGE_TYPE.Laser,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'rifle',
    nRange: 30,
    nPoints: 4,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 15,
    nFireRate: 0.2,
  },
  Plasmatron: {
    sName: 'Plasmatron',
    friendlyName: 'Plasmatron',
    nDamage: 30,
    nDamageType: DAMAGE_TYPE.Laser,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'rifle',
    nRange: 10,
    nPoints: 3,
    nMinAimTime: 1,
    nMaxAimTime: 3,
    nMinCoolDown: 1,
    nMaxCoolDown: 3,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 10,
    nFireRate: 0.4,
  },
  Derezzer: {
    sName: 'Derezzer',
    friendlyName: 'Derezzer',
    nDamage: 25,
    nDamageType: DAMAGE_TYPE.Laser,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'rifle',
    nRange: 12,
    nPoints: 2,
    bJobTool: true,
    bStuff: true,
    nProjectileSpeed: 10,
    nFireRate: 0.5,
  },
  KillbotRifle: {
    sName: 'KillbotRifle',
    friendlyName: 'Killbot Rifle',
    nDamage: 20,
    nDamageType: DAMAGE_TYPE.Laser,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'rifle',
    nRange: 18,
    nPoints: 4,
    bDisappearOnDrop: true,
    nProjectileSpeed: 12,
    nFireRate: 0.3,
  },

  // ── Turret (special) ───────────────────────────────────────────────────────
  TurretLaser: {
    sName: 'TurretLaser',
    friendlyName: 'Turret Laser',
    nDamage: 20,
    nDamageType: DAMAGE_TYPE.Laser,
    nAttackType: ATTACK_TYPE.Ranged,
    sStance: 'rifle',
    nRange: 10,
    nPoints: 0,
    nProjectileSpeed: 15,
    nFireRate: 0.4,
  },
};
