import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['tests/**/*.test.ts'],
    environment: 'node',
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'lcov'],
      reportsDirectory: 'coverage',
      include: [
        'src/save/SaveLoad.ts',
        'src/oxygen/OxygenSystem.ts',
        'src/oxygen/VacuumSystem.ts',
        'src/envobjects/Door.ts',
        'src/pathfinding/AStar.ts',
        'src/events/EventController.ts',
        'src/events/EventData.ts',
        'src/power/PowerSystem.ts',
        'src/research/ResearchSystem.ts',
        'src/utility/Task.ts',
        'src/utility/UtilityAI.ts',
        'src/utility/tasks/AttackEnemy.ts',
        'src/utility/tasks/Cuff.ts',
        'src/utility/tasks/DropEverything.ts',
        'src/utility/tasks/DropOffCorpse.ts',
        'src/utility/tasks/DropOffRocks.ts',
        'src/utility/tasks/Eat.ts',
        'src/utility/tasks/ExtinguishFireBareHanded.ts',
        'src/utility/tasks/ExtinguishFireWithTool.ts',
        'src/utility/tasks/FieldScanAndHeal.ts',
        'src/utility/tasks/FleeThreat.ts',
        'src/utility/tasks/GetFieldScanned.ts',
        'src/utility/tasks/MaintainEnvObject.ts',
        'src/utility/tasks/OxygenFleeArea.ts',
        'src/utility/tasks/PickUpFloorItem.ts',
        'src/utility/tasks/PutOnSuit.ts',
        'src/utility/tasks/ResearchInLab.ts',
        'src/utility/tasks/Sabotage.ts',
        'src/utility/tasks/VacuumPull.ts',
        'src/zones/ResearchZone.ts',
      ],
      thresholds: {
        lines: 58,
        functions: 67,
        statements: 55,
        branches: 47,
      },
    },
  },
});
