import { RoomManager } from '../rooms/RoomManager';
import { EnvObjectManager } from '../envobjects/EnvObjectManager';
import { O2_MAX, O2_DRAIN_RATE } from '../config';

/**
 * OxygenSystem — per-room O2 simulation.
 *
 * Mirrors Oxygen.lua: oxygen is generated by env objects with oxygenLevel > 0
 * (O2 Recyclers). Sealed rooms without a working recycler do NOT fill.
 * Breached rooms always drain to vacuum.
 *
 * Fill rate: each recycler adds oxygenLevel per tick (scaled from Lua units to
 * our 0–255 range). Original Lua tile max is ~65535; we scale to O2_MAX (255)
 * so a Mk I recycler (oxygenLevel 50) fills a room at a reasonable rate.
 */

const LUA_O2_SCALE = 65535; // DFOxygenGrid OXYGEN_TILE_MAX approximation
const O2_FILL_PER_UNIT = O2_MAX / LUA_O2_SCALE; // scale factor per oxygenLevel unit

export class OxygenSystem {
  private roomManager: RoomManager;
  private tickAccumulator = 0;
  private tickInterval = 500; // ms between O2 ticks

  constructor(roomManager: RoomManager) {
    this.roomManager = roomManager;
  }

  update(delta: number) {
    this.tickAccumulator += delta;
    if (this.tickAccumulator < this.tickInterval) return;
    this.tickAccumulator -= this.tickInterval;

    for (const room of this.roomManager.getRooms()) {
      // Airlock running its own O2 cycle — mirrors Airlock:disallowO2Propagation()
      const airlock = room.zoneObj as any;
      if (airlock?.disallowO2Propagation?.()) continue;

      if (!room.sealed) {
        // Breached room: O2 drains to vacuum
        room.oxygen = Math.max(0, room.oxygen - O2_DRAIN_RATE);
        continue;
      }

      // Sealed room: only fills if there's a working O2 recycler in the room
      let totalO2Output = 0;
      for (const obj of EnvObjectManager.getObjectsInRoom(room)) {
        totalO2Output += obj.getOxygenOutput();
      }

      if (totalO2Output > 0) {
        const fillRate = totalO2Output * O2_FILL_PER_UNIT;
        room.oxygen = Math.min(O2_MAX, room.oxygen + fillRate);
      }
      // No recycler → oxygen stays as-is (neither fills nor drains in sealed room)
    }
  }
}
