#!/usr/bin/env python3
"""
extract_atlas_sprites.py — Extract all sprites from the Objects.png atlas.

Parses Objects.lua (TexturePacker/MOAI format) for UV coordinates,
crops each sprite from the 2048x2048 atlas, and saves individual PNGs.

Usage:
    python3 tools/extract_atlas_sprites.py

Output: public/assets/environments/{name}.png for each sprite frame.
Also generates src/renderer/SpriteAtlasData.generated.ts with frame definitions.
"""

import re
import os
import json
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Pillow not installed. Run: pip install Pillow")
    raise SystemExit(1)

# Paths
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
ATLAS_PNG = PROJECT_ROOT / "extracted_assets" / "Environments" / "Objects.png"
OBJECTS_LUA = PROJECT_ROOT / "spacebase-v2-updated-code-master" / "spacebase-v2-updated-code-master" / "Win" / "Munged" / "Environments" / "Objects.lua"
OUTPUT_DIR = PROJECT_ROOT / "public" / "assets" / "environments"


def parse_objects_lua(lua_path: Path) -> list[dict]:
    """Parse Objects.lua TexturePacker output into frame definitions."""
    text = lua_path.read_text()

    frames = []
    # Match each frame block
    frame_pattern = re.compile(
        r'\{\s*'
        r'name\s*=\s*"([^"]+)"\s*,\s*'
        r'spriteColorRect\s*=\s*\{\s*x\s*=\s*([\d.]+)\s*,\s*y\s*=\s*([\d.]+)\s*,\s*width\s*=\s*([\d.]+)\s*,\s*height\s*=\s*([\d.]+)\s*\}\s*,\s*'
        r'uvRect\s*=\s*\{\s*u0\s*=\s*([\d.]+)\s*,\s*v0\s*=\s*([\d.]+)\s*,\s*u1\s*=\s*([\d.]+)\s*,\s*v1\s*=\s*([\d.]+)\s*\}\s*,\s*'
        r'spriteSourceSize\s*=\s*\{\s*width\s*=\s*([\d.]+)\s*,\s*height\s*=\s*([\d.]+)\s*\}\s*,\s*'
        r'spriteTrimmed\s*=\s*(true|false)\s*,\s*'
        r'textureRotated\s*=\s*(true|false)\s*'
        r'\s*\}',
        re.DOTALL
    )

    for m in frame_pattern.finditer(text):
        frames.append({
            "name": m.group(1),
            "colorRect": {
                "x": int(float(m.group(2))),
                "y": int(float(m.group(3))),
                "width": int(float(m.group(4))),
                "height": int(float(m.group(5))),
            },
            "uvRect": {
                "u0": float(m.group(6)),
                "v0": float(m.group(7)),
                "u1": float(m.group(8)),
                "v1": float(m.group(9)),
            },
            "sourceSize": {
                "width": int(float(m.group(10))),
                "height": int(float(m.group(11))),
            },
            "trimmed": m.group(12) == "true",
            "rotated": m.group(13) == "true",
        })

    return frames


def extract_sprite(atlas: Image.Image, frame: dict, output_path: Path):
    """Extract a single sprite from the atlas and save as PNG."""
    atlas_w, atlas_h = atlas.size
    uv = frame["uvRect"]

    # Convert UV (0-1) to pixel coordinates
    px0 = round(uv["u0"] * atlas_w)
    py0 = round(uv["v0"] * atlas_h)
    px1 = round(uv["u1"] * atlas_w)
    py1 = round(uv["v1"] * atlas_h)

    # Crop from atlas
    cropped = atlas.crop((px0, py0, px1, py1))

    # If textureRotated, the sprite is stored rotated 90° CW in the atlas.
    # Rotate 90° CCW to restore original orientation.
    if frame["rotated"]:
        cropped = cropped.rotate(90, expand=True)

    # If trimmed, reconstruct the full-size sprite with transparent padding
    if frame["trimmed"]:
        cr = frame["colorRect"]
        ss = frame["sourceSize"]
        full = Image.new("RGBA", (ss["width"], ss["height"]), (0, 0, 0, 0))

        # After rotation, cropped dimensions should match colorRect width x height
        crop_w, crop_h = cropped.size
        # Paste at the colorRect offset
        full.paste(cropped, (cr["x"], cr["y"]))
        cropped = full

    cropped.save(output_path, "PNG")
    return cropped.size


def generate_ts_data(frames: list[dict], output_path: Path):
    """Generate TypeScript sprite frame definitions for all extracted sprites."""
    lines = [
        "/**",
        " * SpriteAtlasData.generated.ts — Auto-generated sprite frame definitions.",
        " * Generated by tools/extract_atlas_sprites.py. Do not edit manually.",
        " */",
        "",
        "import type { SpriteFrame } from './SpriteAtlasData';",
        "",
        "/** Auto-generated frames from Objects.png atlas extraction. */",
        "export const ATLAS_FRAMES: Record<string, SpriteFrame> = {",
    ]

    sheet_entries: list[tuple[str, str]] = []

    for f in frames:
        name = f["name"]
        ss = f["sourceSize"]
        tex_key = f"sheet_{name}"
        path = f"assets/environments/{name}.png"
        sheet_entries.append((tex_key, path))

        # Each extracted sprite is its own full PNG, so UV covers entire image
        lines.append(f"  {repr(name)}: {{ textureKey: {repr(tex_key)}, u0: 0, v0: 0, u1: 1, v1: 1, sourceW: {ss['width']}, sourceH: {ss['height']} }},")

    lines.append("};")
    lines.append("")
    lines.append("/** Texture entries for all extracted atlas sprites. */")
    lines.append("export const ATLAS_SHEET_ENTRIES: [string, string][] = [")
    for key, path in sheet_entries:
        lines.append(f"  [{repr(key)}, {repr(path)}],")
    lines.append("];")
    lines.append("")

    output_path.write_text("\n".join(lines))


def main():
    print(f"Atlas: {ATLAS_PNG}")
    print(f"Lua:   {OBJECTS_LUA}")
    print(f"Output: {OUTPUT_DIR}")
    print()

    # Parse Lua
    frames = parse_objects_lua(OBJECTS_LUA)
    print(f"Parsed {len(frames)} sprite frames from Objects.lua")

    if not frames:
        print("ERROR: No frames parsed! Check Lua file format.")
        return

    # Load atlas
    atlas = Image.open(ATLAS_PNG).convert("RGBA")
    print(f"Atlas size: {atlas.size[0]}x{atlas.size[1]}")

    # Ensure output directory
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Extract each sprite
    extracted = 0
    for frame in frames:
        out_path = OUTPUT_DIR / f"{frame['name']}.png"
        try:
            size = extract_sprite(atlas, frame, out_path)
            extracted += 1
            rotated_str = " [rotated]" if frame["rotated"] else ""
            print(f"  {frame['name']}: {size[0]}x{size[1]}{rotated_str}")
        except Exception as e:
            print(f"  ERROR extracting {frame['name']}: {e}")

    print(f"\nExtracted {extracted}/{len(frames)} sprites to {OUTPUT_DIR}")

    # Generate TypeScript data
    ts_path = PROJECT_ROOT / "src" / "renderer" / "SpriteAtlasData.generated.ts"
    generate_ts_data(frames, ts_path)
    print(f"Generated {ts_path}")


if __name__ == "__main__":
    main()
